// Code generated by storm v0.6.6. DO NOT EDIT.
// source: table schema_migrations

package schemamigration

import (
	"context"
	"errors"
	"net/netip"
	"time"

	"github.com/gsoultan/storm/runtime"
)

var (
	_ = time.Time{}
	_ = netip.Prefix{}
)

// Row is what a full read returns: the model struct with relations
// replaced by their scalar foreign keys and *T rewritten to Null[T].
type Row struct {
	Name      string
	AppliedAt time.Time
}

// Operator ids. Argument-taking operators are numbered first, so the
// bind loop tests `op-1 < opsWithArg` with one unsigned compare.
const (
	opEq               runtime.Op = 1
	opNotEq            runtime.Op = 2
	opGt               runtime.Op = 3
	opGte              runtime.Op = 4
	opLt               runtime.Op = 5
	opLte              runtime.Op = 6
	opLike             runtime.Op = 7
	opILike            runtime.Op = 8
	opMatches          runtime.Op = 9
	opWebSearch        runtime.Op = 10
	opOverlaps         runtime.Op = 11
	opContainsRange    runtime.Op = 12
	opContainedBy      runtime.Op = 13
	opIn               runtime.Op = 14
	opNotIn            runtime.Op = 15
	opArrayContains    runtime.Op = 16
	opArrayContainedBy runtime.Op = 17
	opArrayOverlaps    runtime.Op = 18
	opJSONContains     runtime.Op = 19
	opJSONContainedBy  runtime.Op = 20
	opHasAnyKey        runtime.Op = 21
	opHasAllKeys       runtime.Op = 22
	opIsNull           runtime.Op = 23
	opIsNotNull        runtime.Op = 24
	// Existence operators apply to PSEUDO-COLUMNS — relation slots past
	// the real columns in the frag table. Argless, like IsNull: the
	// fragment is constant, which is what lets a semi-join ride the
	// ordinary predicate machinery and compose under And/Or/Not free.
	opExists    runtime.Op = 25
	opNotExists runtime.Op = 26
)

const nCols = 2

// Query is a value type: composing one allocates nothing. Predicates
// are a postfix token stream, so disjunction and negation are
// representable — a per-column operator mask cannot express either.
type Query struct {
	toks [16]runtime.Tok
	nt   uint8
	top  uint8 // top-level conjuncts, ANDed at compile time

	strs    [6]string
	tims    [4]time.Time
	ns, ntm uint8

	anyStr [3][]string
	nas    uint8

	// Order terms live in their own buffer and are appended to the stream
	// after the predicate tree. Sharing one buffer would let a Where after
	// an Order interleave the two, and the stream's order is its meaning.
	otoks [4]runtime.Tok
	no    uint8

	// lock is the row-lock mode: 0 none, then pgsql.LockMode order.
	// It is part of the STATEMENT, so it selects the cache as well as
	// the suffix.
	lock uint8

	limit  int64
	offset int64
	// over records that the query outgrew its fixed buffers. Terminals
	// return it as an error rather than silently dropping a predicate.
	over bool

	// mixed records an After() over an ordering that is not all in one
	// direction. No single row comparison expresses that.
	mixed bool

	// noOrder suppresses the default ordering. See Unordered.
	noOrder  bool
	badAfter bool
}

// New starts a query.
func New() Query { return Query{limit: 1000} }

// Limit caps the result set.
func (q Query) Limit(n int64) Query { q.limit = n; return q }

// Offset skips rows.
//
// It is here because callers expect it, not because it is a good idea: the
// database still walks and discards every skipped row, so page 5,000 costs
// 5,000 pages of work, and a row inserted mid-scroll shifts every later
// page. Order by a unique key and filter past the last one you saw instead.
func (q Query) Offset(n int64) Query { q.offset = n; return q }

// After filters past a row already seen: keyset pagination.
//
// The comparison follows the ACTIVE ordering, because it has to. Paging
// `ORDER BY email DESC` with `> $1` walks away from the rows you have
// not seen yet, and silently returns a wrong page rather than an error.
// So After reads the ordering off the query and builds the matching row
// comparison: (a, b) > ($1, $2) for ascending, < for descending.
//
// Unlike Offset the database does not walk the skipped rows — the
// comparison seeks straight into the index — and a row inserted
// mid-scroll cannot shift a page, because the cursor is a position in the
// data rather than a count.
//
// Mixing ascending and descending terms in one ordering is a query error:
// no single row comparison expresses it, and expanding it into ORs would
// silently give up the index walk that makes this worth doing.
func (q Query) After(r Row) Query {
	terms := q.otoks[:q.no]
	if q.no == 0 {
		if q.noOrder {
			// A keyset cursor without an order is a position in nothing.
			q.badAfter = true
			return q
		}
		terms = defaultOrder[:]
	}
	if len(terms) == 0 {
		return q
	}
	desc := terms[0].Op() == runtime.Desc || terms[0].Op() == runtime.DescNullsLast
	for _, t := range terms {
		d := t.Op() == runtime.Desc || t.Op() == runtime.DescNullsLast
		if d != desc {
			q.mixed = true
			return q
		}
	}
	for _, t := range terms {
		q.push(runtime.MakeCol(t.Col()))
		q.cursor(t.Col(), r)
	}
	op := runtime.CmpGt
	if desc {
		op = runtime.CmpLt
	}
	q.push(runtime.MakeRowCmp(op, uint32(len(terms))))
	q.top++
	return q
}

// cursor stores the bound value for one column of a keyset comparison.
func (q *Query) cursor(col uint32, r Row) {
	switch col {
	case 0:
		if int(q.ns) >= len(q.strs) {
			q.over = true
			return
		}
		q.strs[q.ns] = r.Name
		q.ns++
	case 1:
		if int(q.ntm) >= len(q.tims) {
			q.over = true
			return
		}
		q.tims[q.ntm] = r.AppliedAt
		q.ntm++
	}
}

// Unordered drops the default ordering, for results consumed in an
// order-independent way — a batch loader that buckets rows into a map,
// an aggregation, a bulk export.
//
// The default exists because paging an unordered read is a bug; the
// escape exists because ordering a read NOBODY PAGES is a server-side
// sort for free. Measured on a 50k-row relation load: an external merge
// sort spilling 5MB to disk, for an order the loader's map bucketing
// destroyed on arrival. An explicit Order() still applies; After() on an
// unordered query with no explicit order is an error, because a keyset
// cursor without an order is a position in nothing.
func (q Query) Unordered() Query { q.noOrder = true; return q }

// Row locking.
//
// A lock is held to the end of the TRANSACTION, so one taken outside a
// transaction is released before the next statement runs and protects
// nothing — pass a pgxdrv.Tx, not a pool.
//
// Locking is refused on Count and Exists, and on the declared
// aggregations and joins. The server rejects a row lock combined with an
// aggregate, a grouping, a DISTINCT or a set operation, and on the
// nullable side of an outer join; refusing at the call site names the
// rule, where the server would name a SQLSTATE.
//
// The two weakest strengths are deliberately absent. They exist for the
// deadlock between updating a parent row and inserting a child that
// references it, which is real and rare, and a caller who has it knows
// the exact SQL they want — storm.SQL gives it to them typed.

// ForUpdate locks the rows this query returns, and takes the strongest row lock, waiting for anyone who already holds it.
func (q Query) ForUpdate() Query { q.lock = 1; return q }

// ForUpdateNoWait locks the rows this query returns, and fails immediately rather than wait for a lock someone else holds.
func (q Query) ForUpdateNoWait() Query { q.lock = 2; return q }

// ForUpdateSkipLocked locks the rows this query returns, and steps over the rows another transaction has locked. This is the queue claim, and the one form that returns FEWER rows than Limit asks for: that is the point of it, not a fault.
func (q Query) ForUpdateSkipLocked() Query { q.lock = 3; return q }

// ForShare locks the rows this query returns, and blocks writers while letting other readers share the lock.
func (q Query) ForShare() Query { q.lock = 4; return q }

// ForShareNoWait locks the rows this query returns, and is the shared lock, failing rather than waiting.
func (q Query) ForShareNoWait() Query { q.lock = 5; return q }

// ForShareSkipLocked locks the rows this query returns, and is the shared lock, stepping over rows another transaction holds.
func (q Query) ForShareSkipLocked() Query { q.lock = 6; return q }

// Sort is one ORDER BY term, produced by a column handle: Email.Asc().
type Sort runtime.Tok

// Order replaces the ordering. Passing none restores the default.
//
// An ordering is part of a statement's identity, not a decoration on it:
// two queries differing only in ORDER BY are different statements, so the
// terms join the token stream that keys the compiled-statement cache.
func (q Query) Order(ts ...Sort) Query {
	q.no = 0
	for _, t := range ts {
		if int(q.no) >= len(q.otoks) {
			q.over = true
			return q
		}
		q.otoks[q.no] = runtime.Tok(t)
		q.no++
	}
	return q
}

// Err reports a query that outgrew its buffers.
func (q Query) Err() error {
	if q.over {
		return errTooComplex
	}
	if q.mixed {
		return errMixedOrder
	}
	if q.badAfter {
		return errAfterUnordered
	}
	return nil
}

var errAfterUnordered = errors.New(
	"storm: After() on an Unordered() query with no explicit Order — a keyset cursor without an ordering is a position in nothing")

var errMixedOrder = errors.New(
	"storm: After() needs every ORDER BY term in the same direction; a mixed ordering has no single row comparison, and expanding it into ORs gives up the index walk that makes keyset pagination worth doing")

var errCountLocked = errors.New(
	"storm: a locked read cannot be counted — the server refuses a row lock with an aggregate; count first, then lock the rows you take")

var errExistsLocked = errors.New(
	"storm: a locked read cannot be an existence probe — locking a row to answer a boolean is a row nobody reads; use One() with the same lock")

var errTooComplex = errors.New(
	"storm: query has more predicates than the generated buffers hold (scale 1); split the query, or regenerate with a larger codegen.Budgets{Scale}")

// push and leaf mutate through a pointer so the builder loop does not
// copy the whole Query twice per predicate. They are only ever called on
// a local, so the public API keeps value semantics: q2 := q1.Where(x)
// must not mutate q1.
func (q *Query) push(t runtime.Tok) {
	if int(q.nt) >= len(q.toks) {
		q.over = true
		return
	}
	q.toks[q.nt] = t
	q.nt++
}

// preds returns the predicate stream with top-level conjuncts ANDed.
// A count uses this: ordering a scalar is wasted work, and including the
// terms would compile a second statement per ordering for no difference.
func (q Query) preds(buf *[21]runtime.Tok) []runtime.Tok {
	n := copy(buf[:], q.toks[:q.nt])
	if q.top > 1 {
		buf[n] = runtime.MakeGroup(runtime.KAnd, uint32(q.top))
		n++
	}
	return buf[:n]
}

// stream is the predicates followed by the ordering — the whole statement
// key. Order tokens go last so a splicer can find the boundary by kind.
func (q Query) stream(buf *[21]runtime.Tok) []runtime.Tok {
	n := len(q.preds(buf))
	if q.no == 0 {
		if q.noOrder {
			return buf[:n]
		}
		n += copy(buf[n:], defaultOrder[:])
		return buf[:n]
	}
	n += copy(buf[n:], q.otoks[:q.no])
	return buf[:n]
}

// Pred is one predicate, produced by a typed column handle. A value with
// a small union payload: no interface, nothing to allocate. Structure is
// assembled by Query into a token stream — see Where/Any/Not.
type Pred struct {
	col    uint8
	op     runtime.Op
	str    string
	tim    time.Time
	anyStr []string
}

// Typed column handles. The type of the handle is what makes
// Age.Like(...) fail to compile.
var (
	Name      = TextCol{0}
	AppliedAt = TimeCol{1}
)

// TextCol addresses a text column.
type TextCol struct{ c uint8 }

func (h TextCol) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h TextCol) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h TextCol) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h TextCol) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

func (h TextCol) Eq(v string) Pred    { return Pred{col: h.c, op: opEq, str: v} }
func (h TextCol) NotEq(v string) Pred { return Pred{col: h.c, op: opNotEq, str: v} }
func (h TextCol) Gt(v string) Pred    { return Pred{col: h.c, op: opGt, str: v} }
func (h TextCol) Gte(v string) Pred   { return Pred{col: h.c, op: opGte, str: v} }
func (h TextCol) Lt(v string) Pred    { return Pred{col: h.c, op: opLt, str: v} }
func (h TextCol) Lte(v string) Pred   { return Pred{col: h.c, op: opLte, str: v} }
func (h TextCol) Like(v string) Pred  { return Pred{col: h.c, op: opLike, str: v} }
func (h TextCol) ILike(v string) Pred { return Pred{col: h.c, op: opILike, str: v} }
func (h TextCol) In(v ...string) Pred { return Pred{col: h.c, op: opIn, anyStr: v} }

// NotIn is `<> ALL($1)`. A NULL anywhere in v makes the
// comparison NULL for every row and the result empty —
// PostgreSQL's rule for NOT IN, not storm's.
func (h TextCol) NotIn(v ...string) Pred { return Pred{col: h.c, op: opNotIn, anyStr: v} }

// TimeCol addresses a timestamptz column.
type TimeCol struct{ c uint8 }

func (h TimeCol) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h TimeCol) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h TimeCol) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h TimeCol) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

func (h TimeCol) Eq(v time.Time) Pred    { return Pred{col: h.c, op: opEq, tim: v} }
func (h TimeCol) NotEq(v time.Time) Pred { return Pred{col: h.c, op: opNotEq, tim: v} }
func (h TimeCol) Gt(v time.Time) Pred    { return Pred{col: h.c, op: opGt, tim: v} }
func (h TimeCol) Gte(v time.Time) Pred   { return Pred{col: h.c, op: opGte, tim: v} }
func (h TimeCol) Lt(v time.Time) Pred    { return Pred{col: h.c, op: opLt, tim: v} }
func (h TimeCol) Lte(v time.Time) Pred   { return Pred{col: h.c, op: opLte, tim: v} }

// Where applies predicates, ANDed together.
func (q Query) Where(ps ...Pred) Query {
	for i := range ps {
		q.leaf(ps[i])
		q.top++
	}
	return q
}

// WhenSet applies f(*v) only when v is non-nil — the optional-filter
// idiom without an if, and without the nil dereference WhereIf invites.
//
//	q = user.WhenSet(q, f.MinAge, user.Age.Gte)
//
// WhereIf takes an already-built Pred, so the caller has to evaluate
// user.Age.Gte(*f.MinAge) BEFORE the condition is tested — which panics
// on exactly the nil the condition was checking for. This takes the
// constructor instead, so nothing is dereferenced unless it is there.
//
// It still sets exactly one bit in the shape mask: a filter that is
// absent is a different SHAPE, compiled once, not a different value.
func WhenSet[T any](q Query, v *T, f func(T) Pred) Query {
	if v == nil {
		return q
	}
	return q.Where(f(*v))
}

// WhereIf applies a predicate only when cond holds.
func (q Query) WhereIf(cond bool, p Pred) Query {
	if !cond {
		return q
	}
	return q.Where(p)
}

// Any ORs its arguments and ANDs the group with the rest of the query:
// Where(a).Any(b, c) is a AND (b OR c).
func (q Query) Any(ps ...Pred) Query {
	if len(ps) == 0 {
		return q
	}
	for i := range ps {
		q.leaf(ps[i])
	}
	q.push(runtime.MakeGroup(runtime.KOr, uint32(len(ps))))
	q.top++
	return q
}

// Not negates one predicate and ANDs it with the rest.
func (q Query) Not(p Pred) Query {
	q.leaf(p)
	q.push(runtime.MakeGroup(runtime.KNot, 1))
	q.top++
	return q
}

// NotAny negates a disjunction: NOT (a OR b).
func (q Query) NotAny(ps ...Pred) Query {
	if len(ps) == 0 {
		return q
	}
	for i := range ps {
		q.leaf(ps[i])
	}
	q.push(runtime.MakeGroup(runtime.KOr, uint32(len(ps))))
	q.push(runtime.MakeGroup(runtime.KNot, 1))
	q.top++
	return q
}

// Grp is one conjunction, built by And, that AnyOf ORs with the others.
//
// It holds the predicates rather than tokens because the ARENA a value
// lands in is chosen by leaf, in stream order, and a group has no stream
// position until AnyOf gives it one.
type Grp struct{ ps []Pred }

// And groups predicates into one conjunction, so AnyOf can OR whole
// conjunctions rather than single predicates:
//
//	q.AnyOf(And(Status.Eq("paid"), Total.Gt(big)),
//	        And(Status.Eq("trial"), Total.Gt(small)))
//
// is (status = $1 AND total > $2) OR (status = $3 AND total > $4). Any
// ORs single predicates and cannot say this: an advanced-search screen
// whose rows are each a field, an operator and a value produces exactly
// this shape, and without it the query has to be written in SQL.
//
// The variadic slice does not escape — AnyOf reads it and returns — so a
// warm call still builds its SQL without allocating.
func And(ps ...Pred) Grp { return Grp{ps: ps} }

// AnyOf ORs its groups and ANDs the result with the rest of the query.
//
// An empty group contributes nothing, so a screen that builds one group
// per filled-in filter row needs no special case for the rows the user
// left blank. A group of one predicate is that predicate: the SQL carries
// no parentheses it did not need, which keeps the statement — and so the
// shape it is cached under — the same as the equivalent Any.
func (q Query) AnyOf(gs ...Grp) Query {
	n := uint32(0)
	for i := range gs {
		if len(gs[i].ps) == 0 {
			continue
		}
		for j := range gs[i].ps {
			q.leaf(gs[i].ps[j])
		}
		if len(gs[i].ps) > 1 {
			q.push(runtime.MakeGroup(runtime.KAnd, uint32(len(gs[i].ps))))
		}
		n++
	}
	if n == 0 {
		return q
	}
	if n > 1 {
		q.push(runtime.MakeGroup(runtime.KOr, n))
	}
	q.top++
	return q
}

// NotAnyOf negates the disjunction AnyOf builds: NOT ((a AND b) OR c).
func (q Query) NotAnyOf(gs ...Grp) Query {
	before := q.top
	q = q.AnyOf(gs...)
	if q.top == before {
		return q
	}
	q.push(runtime.MakeGroup(runtime.KNot, 1))
	return q
}

// leaf records one predicate: its value goes to the arena for its type,
// its structure to the token stream.
func (q *Query) leaf(p Pred) {
	if p.op == opIn || p.op == opNotIn || p.op == opArrayContains || p.op == opArrayContainedBy || p.op == opArrayOverlaps || p.op == opHasAnyKey || p.op == opHasAllKeys {
		switch p.col {
		case 0:
			if int(q.nas) >= 3 {
				q.over = true
				return
			}
			q.anyStr[q.nas] = p.anyStr
			q.nas++
		}
		q.push(runtime.MakeLeaf(uint32(p.op), uint32(p.col)))
		return
	}
	switch p.col {
	case 0:
		if int(q.ns) >= 6 {
			q.over = true
			return
		}
		q.strs[q.ns] = p.str
		q.ns++
	case 1:
		if int(q.ntm) >= 4 {
			q.over = true
			return
		}
		q.tims[q.ntm] = p.tim
		q.ntm++
	}
	q.push(runtime.MakeLeaf(uint32(p.op), uint32(p.col)))
}

// Chained predicate sugar. Identical to Where(Col.Op(v)).
func (q Query) NameEq(v string) Query            { return q.Where(Name.Eq(v)) }
func (q Query) NameNotEq(v string) Query         { return q.Where(Name.NotEq(v)) }
func (q Query) NameGt(v string) Query            { return q.Where(Name.Gt(v)) }
func (q Query) NameGte(v string) Query           { return q.Where(Name.Gte(v)) }
func (q Query) NameLt(v string) Query            { return q.Where(Name.Lt(v)) }
func (q Query) NameLte(v string) Query           { return q.Where(Name.Lte(v)) }
func (q Query) NameLike(v string) Query          { return q.Where(Name.Like(v)) }
func (q Query) NameILike(v string) Query         { return q.Where(Name.ILike(v)) }
func (q Query) NameIn(v ...string) Query         { return q.Where(Name.In(v...)) }
func (q Query) NameNotIn(v ...string) Query      { return q.Where(Name.NotIn(v...)) }
func (q Query) AppliedAtEq(v time.Time) Query    { return q.Where(AppliedAt.Eq(v)) }
func (q Query) AppliedAtNotEq(v time.Time) Query { return q.Where(AppliedAt.NotEq(v)) }
func (q Query) AppliedAtGt(v time.Time) Query    { return q.Where(AppliedAt.Gt(v)) }
func (q Query) AppliedAtGte(v time.Time) Query   { return q.Where(AppliedAt.Gte(v)) }
func (q Query) AppliedAtLt(v time.Time) Query    { return q.Where(AppliedAt.Lt(v)) }
func (q Query) AppliedAtLte(v time.Time) Query   { return q.Where(AppliedAt.Lte(v)) }

const selectPrefix = `SELECT "name", "applied_at" FROM "schema_migrations"`
const countPrefix = `SELECT count(*) FROM "schema_migrations"`
const existsPrefix = `SELECT 1 FROM "schema_migrations"`
const existsSuffix = ` LIMIT 1`
const limitSuffix = ` LIMIT $`
const limitOffsetSuffix = ` LIMIT $ OFFSET $`

// lockSuffix is the row-lock clause per mode, indexed by Query.lock.
// It goes at the very END of the statement — after LIMIT and OFFSET,
// which is what the grammar requires.
var lockSuffix = [7]string{
	``,
	` FOR UPDATE`,
	` FOR UPDATE NOWAIT`,
	` FOR UPDATE SKIP LOCKED`,
	` FOR SHARE`,
	` FOR SHARE NOWAIT`,
	` FOR SHARE SKIP LOCKED`,
}

// lockCaches holds one compiled-statement cache per (lock, offset)
// pair. The lock is part of the STATEMENT, so it has to be part of the
// key; a program that never locks never touches the locked entries and
// they stay the empty maps they start as.
var lockCaches = func() [7][2]*runtime.TreeCache {
	var cs [7][2]*runtime.TreeCache
	for i := range cs {
		cs[i][0], cs[i][1] = runtime.NewTreeCache(), runtime.NewTreeCache()
	}
	cs[0][0], cs[0][1] = cache, offsetCache
	return cs
}()

// orderTable is every ordering this table can express, lowered at build
// time. ORDER BY is chosen per query, so it cannot be a constant — but it
// still must not be built from strings at run time.
var orderTable = [nCols][4]string{
	{ // name
		"\"name\"",
		"\"name\" DESC",
		"\"name\" ASC NULLS FIRST",
		"\"name\" DESC NULLS LAST",
	},
	{ // applied_at
		"\"applied_at\"",
		"\"applied_at\" DESC",
		"\"applied_at\" ASC NULLS FIRST",
		"\"applied_at\" DESC NULLS LAST",
	},
}

// identTable is each column's bare quoted name, for the left side of a
// row comparison.
var identTable = [nCols]string{
	"\"name\"",
	"\"applied_at\"",
}

var lowering = runtime.Lowering{
	Frag:  fragOf,
	Order: orderOf,
	OB:    runtime.Order{Lead: " ORDER BY ", Sep: ", "},
	Ident: func(col uint32) string {
		if col >= nCols {
			return ""
		}
		return identTable[col]
	},
	RowCmp: func(op uint32) string {
		if op == runtime.CmpLt {
			return " < "
		}
		return " > "
	},
	TupleOpen:  "(",
	TupleSep:   ", ",
	TupleClose: ")",
}

func orderOf(dir, col uint32) string {
	if col >= nCols || int(dir) >= len(orderTable[0]) {
		return ""
	}
	return orderTable[col][dir]
}

// fragTable is every predicate this table can produce, lowered at build
// time. Runtime splices; it never formats.
var fragTable = [2][27]runtime.Frag{
	{ // name
		{}, // opNone
		{A: "\"name\" = $", B: ""},
		{A: "\"name\" <> $", B: ""},
		{A: "\"name\" > $", B: ""},
		{A: "\"name\" >= $", B: ""},
		{A: "\"name\" < $", B: ""},
		{A: "\"name\" <= $", B: ""},
		{A: "\"name\" LIKE $", B: ""},
		{A: "\"name\" ILIKE $", B: ""},
		{},
		{},
		{},
		{},
		{},
		{A: "\"name\" = ANY($", B: ")"},
		{A: "\"name\" <> ALL($", B: ")"},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
	},
	{ // applied_at
		{}, // opNone
		{A: "\"applied_at\" = $", B: ""},
		{A: "\"applied_at\" <> $", B: ""},
		{A: "\"applied_at\" > $", B: ""},
		{A: "\"applied_at\" >= $", B: ""},
		{A: "\"applied_at\" < $", B: ""},
		{A: "\"applied_at\" <= $", B: ""},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
	},
}

func fragOf(op, col uint32) runtime.Frag {
	// Bounded by the table, not nCols: existence pseudo-columns live past
	// the real ones. Order, ident and arena lookups stay nCols-bounded,
	// so a pseudo-column can never be ordered by, cursored on, or bound.
	if int(col) >= len(fragTable) || int(op) >= len(fragTable[0]) {
		return runtime.Frag{}
	}
	return fragTable[col][op]
}

// defaultOrder is what a query with no Order() uses.
//
// It is never empty. A read without ORDER BY has no defined order, so
// paging one is a bug waiting for a plan change to expose it — and the
// primary key is the cheapest total order available.
var defaultOrder = [1]runtime.Tok{
	runtime.MakeOrder(runtime.Asc, 0), // name
}

var (
	cache       = runtime.NewTreeCache()
	offsetCache = runtime.NewTreeCache()
	countCache  = runtime.NewTreeCache()
	existsCache = runtime.NewTreeCache()
)

// Shapes reports how many distinct query structures have compiled.
// `storm lint` uses it to catch a builder minting a statement per request.
func Shapes() int { return cache.Shapes() }

// ShapeFlushes reports how many times a shape cache in this package hit
// runtime.ShapeCap and dropped. Zero is the expected value forever:
// nonzero means a call site is minting structures from request data
// rather than from code, and the fix is that call site, not a bigger
// cap. Export it as a gauge — it is the cheapest early warning that a
// filter screen turned into 2^n statements.
func ShapeFlushes() int {
	return cache.Flushes() + offsetCache.Flushes() +
		countCache.Flushes() + existsCache.Flushes()
}

// stmtFor compiles a read. LIMIT and LIMIT/OFFSET are different
// statements with different placeholder counts, so they get different
// caches rather than a sentinel token muddying the key.
func stmtFor(toks []runtime.Tok, withOffset bool, lock uint8) *runtime.Stmt {
	i, suffix := 0, limitSuffix
	if withOffset {
		i, suffix = 1, limitOffsetSuffix
	}
	c := lockCaches[lock][i]
	suffix += lockSuffix[lock]
	if st := c.Get(toks); st != nil {
		return st
	}
	return c.Put(toks, runtime.SpliceTree(selectPrefix, toks, lowering, suffix))
}

// existsStmtFor compiles the existence probe: SELECT 1, no ORDER BY,
// LIMIT 1 — the planner stops at the first matching tuple instead of
// sorting every match to return the "first" of an order nobody reads.
func existsStmtFor(toks []runtime.Tok) *runtime.Stmt {
	if st := existsCache.Get(toks); st != nil {
		return st
	}
	return existsCache.Put(toks, runtime.SpliceTree(existsPrefix, toks, lowering, existsSuffix))
}

func countStmtFor(toks []runtime.Tok) *runtime.Stmt {
	if st := countCache.Get(toks); st != nil {
		return st
	}
	// A count ignores ordering as well as LIMIT: ordering a scalar is
	// wasted work, and the token stream is trimmed before it gets here.
	return countCache.Put(toks, runtime.SpliceTree(countPrefix, toks, lowering, ""))
}

// Composition seams, for the generated CONTEXT package and it alone:
// cross-table statements (a filtered semi-join spans two packages) are
// assembled there from each side's tokens, fragments and bindings. Ids
// only — no SQL text and no value crosses here.

// FragOf is the compiled fragment table, exported for composition.
func FragOf(op, col uint32) runtime.Frag { return fragOf(op, col) }

// Lowering is this package's back-end text, exported for composition.
func Lowering() runtime.Lowering { return lowering }

// StmtPieces are the statement's constant parts, exported for composition.
func StmtPieces() (selectPfx, countPfx, limitSfx string) {
	return selectPrefix, countPrefix, limitSuffix
}

// PredToks appends this query's predicate stream to dst: top-level
// conjuncts reduced to one entry, order excluded.
func (q Query) PredToks(dst []runtime.Tok) []runtime.Tok {
	var buf [21]runtime.Tok
	return append(dst, q.preds(&buf)...)
}

// OrderToks appends this query's ordering — explicit, or the default
// unless Unordered.
func (q Query) OrderToks(dst []runtime.Tok) []runtime.Tok {
	if q.no == 0 {
		if q.noOrder {
			return dst
		}
		return append(dst, defaultOrder[:]...)
	}
	return append(dst, q.otoks[:q.no]...)
}

// BindPreds binds this query's predicate values into b, appending to v.
func (q Query) BindPreds(b *Binder, v []any) []any {
	return append(v, q.bindPreds(b)...)
}

// BindPaging appends the LIMIT (and OFFSET when set) arguments.
func (q Query) BindPaging(b *Binder, v []any) []any {
	b.limit = q.limit
	v = append(v, &b.limit)
	if q.offset > 0 {
		b.offset = q.offset
		v = append(v, &b.offset)
	}
	return v
}

// Shape is a fingerprint of this query's structure — equal shapes share a
// compiled statement. Values do not contribute, which is the point.
func (q Query) Shape() uint64 {
	var buf [21]runtime.Tok
	return runtime.HashToks(q.stream(&buf))
}

// SQL returns the compiled text for this query's structure.
func (q Query) SQL() string {
	var buf [21]runtime.Tok
	return stmtFor(q.stream(&buf), q.offset > 0, q.lock).SQL
}

// Scan decodes one row from raw wire bytes into r, copying text into sl.
//
// Exported for the context package, which assembles batched results and
// therefore has to decode rows it did not issue the query for.
func Scan(rv [][]byte, r *Row, sl *runtime.Slab) error { return scan(rv, r, sl) }

// scan decodes one row straight from the wire. No reflect, no `any`, no
// driver.Value: the generator knows every column's type already.
//
// It returns an error only for a value the Go type cannot carry — a
// numeric past 18 significant digits, or a NaN. Those must not become a
// plausible zero, and a row scanner is the last place that can tell.
func scan(rv [][]byte, r *Row, sl *runtime.Slab) error {
	r.Name = sl.Str(rv[0])
	r.AppliedAt = runtime.Timestamptz(rv[1])
	return nil
}

type binder struct {
	vals   []any
	strs   [6]string
	tims   [4]time.Time
	anyStr [3][]string
	limit  int64
	offset int64
}

var binders = runtime.NewPool(func() *binder {
	return &binder{vals: make([]any, 0, 17)}
})

// Binder is the pooled argument buffer.
type Binder = binder

func GetBinder() *Binder  { return binders.Get() }
func PutBinder(b *Binder) { putBinder(b) }

// putBinder clears every field that references memory OUTSIDE the binder
// before pooling it. A pooled binder otherwise PINS the caller's data —
// the slice behind an In(...) and the bytes behind every bound string —
// for as long as the pool holds it, which is forever. The numeric, time
// and uuid arenas are value arrays and pin nothing; vals points at the
// binder's own fields. A few nil stores against a round trip is free.
func putBinder(b *binder) {
	for i := range b.strs {
		b.strs[i] = ""
	}
	for i := range b.anyStr {
		b.anyStr[i] = nil
	}
	binders.Put(b)
}

// bindPreds copies arena values into the pooled buffer and points the
// []any at the buffer's own fields — boxing a pointer does not allocate.
// Count and Exists stop here: their statements carry no LIMIT or OFFSET.
func (q Query) bindPreds(b *binder) []any {
	v := b.vals[:0]
	var ns, ntm, nas uint8
	for i := uint8(0); i < q.nt; i++ {
		t := q.toks[i]
		// KLeaf binds a predicate's value; KCol binds a keyset cursor's.
		// Both live in the same per-type arenas in stream order, so the
		// column switch below handles them identically. A KCol carries no
		// operator — its op is opNone, which matches no case in the
		// operator switch and falls straight through.
		if k := t.Kind(); k != runtime.KLeaf && k != runtime.KCol {
			continue
		}
		switch runtime.Op(t.Op()) {
		case opIsNull, opIsNotNull:
			continue
		case opIn, opNotIn, opArrayContains, opArrayContainedBy, opArrayOverlaps, opHasAnyKey, opHasAllKeys:
			switch t.Col() {
			case 0:
				b.anyStr[nas] = q.anyStr[nas]
				v = append(v, &b.anyStr[nas])
				nas++
			}
			continue
		}
		switch t.Col() {
		case 0:
			b.strs[ns] = q.strs[ns]
			v = append(v, &b.strs[ns])
			ns++
		case 1:
			b.tims[ntm] = q.tims[ntm]
			v = append(v, &b.tims[ntm])
			ntm++
		}
	}
	b.vals = v
	return v
}

// bind is bindPreds plus the paging arguments, in suffix order.
func (q Query) bind(b *binder) []any {
	v := q.bindPreds(b)
	b.limit = q.limit
	v = append(v, &b.limit)
	// An offset of zero is absent from the statement, so binding it
	// would leave an argument nothing consumes.
	if q.offset > 0 {
		b.offset = q.offset
		v = append(v, &b.offset)
	}
	b.vals = v
	return v
}

// All runs the query and decodes every row.
func (q Query) All(ctx context.Context, ex runtime.Executor, dst []Row) ([]Row, error) {
	var sl runtime.Slab
	return q.AllInto(ctx, ex, dst, &sl)
}

// AllInto lets the caller own the string arena.
func (q Query) AllInto(ctx context.Context, ex runtime.Executor, dst []Row, sl *runtime.Slab) ([]Row, error) {
	if err := q.Err(); err != nil {
		return dst, err
	}
	var buf [21]runtime.Tok
	st := stmtFor(q.stream(&buf), q.offset > 0, q.lock)
	if st.Err != nil {
		// A malformed token stream is a code-generation bug. Executing it
		// would run a query whose filter is not the one that was asked for.
		return dst, st.Err
	}
	sl.Reserve(st.SlabHint())
	b := binders.Get()
	defer putBinder(b)

	rows, err := ex.Query(ctx, st.SQL, q.bind(b))
	if err != nil {
		return dst, err
	}
	defer rows.Close()
	for rows.Next() {
		dst = append(dst, Row{})
		if err := scan(rows.RawValues(), &dst[len(dst)-1], sl); err != nil {
			return dst, err
		}
	}
	st.ObserveSlab(sl.Size())
	return dst, rows.Err()
}

// One returns the first row, if any.
func (q Query) One(ctx context.Context, ex runtime.Executor) (Row, bool, error) {
	var sl runtime.Slab
	var buf [1]Row
	out, err := q.Limit(1).AllInto(ctx, ex, buf[:0], &sl)
	if err != nil || len(out) == 0 {
		return Row{}, false, err
	}
	return out[0], true, nil
}

// Count ignores Limit: counting a truncated set is a bug, not a feature.
func (q Query) Count(ctx context.Context, ex runtime.Executor) (int64, error) {
	if err := q.Err(); err != nil {
		return 0, err
	}
	if q.lock != 0 {
		return 0, errCountLocked
	}
	var buf [21]runtime.Tok
	st := countStmtFor(q.preds(&buf))
	if st.Err != nil {
		// A malformed token stream is a code-generation bug. Executing it
		// would run a query whose filter is not the one that was asked for.
		return 0, st.Err
	}
	b := binders.Get()
	defer putBinder(b)
	// bindPreds, not bind: a count has no LIMIT and no OFFSET. The old
	// form bound everything and sliced the last argument off, which was
	// the limit — unless Offset was set, in which case it silently kept
	// the limit and dropped the offset, and the statement mismatched.
	rows, err := ex.Query(ctx, st.SQL, q.bindPreds(b))
	if err != nil {
		return 0, err
	}
	defer rows.Close()
	var n int64
	if rows.Next() {
		n = runtime.Int8(rows.RawValues()[0])
	}
	return n, rows.Err()
}

// Exists asks the one-bit question with a one-bit statement: SELECT 1,
// no ORDER BY, LIMIT 1. It was previously One() with the row thrown
// away, which projected every column AND carried the default ordering —
// measured on 50k rows, the planner top-N-sorted all 16,667 matches to
// return the "first" of an order nobody was going to read.
func (q Query) Exists(ctx context.Context, ex runtime.Executor) (bool, error) {
	if err := q.Err(); err != nil {
		return false, err
	}
	if q.lock != 0 {
		return false, errExistsLocked
	}
	var buf [21]runtime.Tok
	st := existsStmtFor(q.preds(&buf))
	if st.Err != nil {
		return false, st.Err
	}
	b := binders.Get()
	defer putBinder(b)
	rows, err := ex.Query(ctx, st.SQL, q.bindPreds(b))
	if err != nil {
		return false, err
	}
	defer rows.Close()
	return rows.Next(), rows.Err()
}

// Prepare resolves the structure and binds arguments without executing.
func (q Query) Prepare(b *Binder) (string, []any) {
	var buf [21]runtime.Tok
	return stmtFor(q.stream(&buf), q.offset > 0, q.lock).SQL, q.bind(b)
}

// No write API: table schema_migrations has no primary key, so no statement can
// address a single row.
// Add one to the model to get Insert, Update and Delete.
