// Code generated by storm v0.6.6. DO NOT EDIT.
// source: bounded context rgen

package rgen

import (
	"context"
	"fmt"

	"github.com/gsoultan/argus/internal/control/rgen/asset"
	"github.com/gsoultan/argus/internal/control/rgen/recoverycode"
	"github.com/gsoultan/argus/internal/control/rgen/session"
	"github.com/gsoultan/argus/internal/control/rgen/user"
	"github.com/gsoultan/storm/runtime"
)

// FlushOrder ranks tables so that every table's foreign-key targets rank
// strictly lower. It is computed at generate time from the model, so no
// runtime code inspects a schema and no constraint has to be deferred for
// a graph write to succeed.
var FlushOrder = map[string]int{
	"access_requests":   0,
	"agents":            1,
	"assets":            2,
	"audit_events":      3,
	"gateway_policy":    4,
	"host_key_pins":     5,
	"redeemed_tickets":  6,
	"schema_migrations": 7,
	"sessions":          8,
	"users":             9,
	"recovery_codes":    10,
}

// NewUnit stages writes across this context and flushes them in foreign-key
// order as one round trip.
func NewUnit() *runtime.Unit { return runtime.NewUnit(FlushOrder) }

// defaultChildLimit caps a relation load. Any constant is arbitrary — too
// low truncates a legitimate load, too high is the unbounded read the dba
// profile vetoes — so what is settled here is only the BEHAVIOUR on
// reaching it: an error, never a partial result. Override per plan with
// ChildLimit.
const defaultChildLimit = 1 << 20

// RecoveryCodeWithUserRow is recovery_codes with its User loaded.
type RecoveryCodeWithUserRow struct {
	recoverycode.Row
	User user.Row
}

type RecoveryCodeWithUserQuery struct {
	q recoverycode.Query
}

// RecoveryCodeWithUser starts the plan.
func RecoveryCodeWithUser() RecoveryCodeWithUserQuery {
	return RecoveryCodeWithUserQuery{q: recoverycode.New()}
}

func (p RecoveryCodeWithUserQuery) Where(ps ...recoverycode.Pred) RecoveryCodeWithUserQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p RecoveryCodeWithUserQuery) WhereIf(cond bool, pr recoverycode.Pred) RecoveryCodeWithUserQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p RecoveryCodeWithUserQuery) Any(ps ...recoverycode.Pred) RecoveryCodeWithUserQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p RecoveryCodeWithUserQuery) Not(pr recoverycode.Pred) RecoveryCodeWithUserQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p RecoveryCodeWithUserQuery) NotAny(ps ...recoverycode.Pred) RecoveryCodeWithUserQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p RecoveryCodeWithUserQuery) Order(ts ...recoverycode.Sort) RecoveryCodeWithUserQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p RecoveryCodeWithUserQuery) Limit(n int64) RecoveryCodeWithUserQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p RecoveryCodeWithUserQuery) Offset(n int64) RecoveryCodeWithUserQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p RecoveryCodeWithUserQuery) After(r RecoveryCodeWithUserRow) RecoveryCodeWithUserQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p RecoveryCodeWithUserQuery) Err() error { return p.q.Err() }

// All runs the plan in exactly TWO round trips. Distinct parent keys are
// de-duplicated before the second, so a thousand rows pointing at three
// orgs fetch three orgs.
func (p RecoveryCodeWithUserQuery) All(ctx context.Context, ex runtime.Executor) ([]RecoveryCodeWithUserRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]RecoveryCodeWithUserRow, len(parents))
	seen := make(map[[16]byte]bool, len(parents))
	ids := make([][16]byte, 0, len(parents))
	for i, r := range parents {
		out[i] = RecoveryCodeWithUserRow{Row: r}
		key := r.UserID
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return out, nil
	}
	targets, err := user.New().Unordered().
		Where(user.ID.In(ids...)).
		Limit(int64(len(ids))).
		All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key := out[i].UserID
		j, ok := by[key]
		if !ok {
			// A foreign key pointing at a row that is not there. The database
			// forbids it, so reaching this means the constraint was dropped.
			return nil, fmt.Errorf("storm: %s references a missing %s row", "recovery_codes", "users")
		}
		out[i].User = targets[j]
	}
	return out, nil
}

// SessionWithAssetRow is sessions with its Asset loaded.
type SessionWithAssetRow struct {
	session.Row
	// A pointer because the link is optional. nil means the row has no
	// Asset, which is different from having one that failed to load.
	Asset *asset.Row
}

type SessionWithAssetQuery struct {
	q session.Query
}

// SessionWithAsset starts the plan.
func SessionWithAsset() SessionWithAssetQuery { return SessionWithAssetQuery{q: session.New()} }

func (p SessionWithAssetQuery) Where(ps ...session.Pred) SessionWithAssetQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p SessionWithAssetQuery) WhereIf(cond bool, pr session.Pred) SessionWithAssetQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p SessionWithAssetQuery) Any(ps ...session.Pred) SessionWithAssetQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p SessionWithAssetQuery) Not(pr session.Pred) SessionWithAssetQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p SessionWithAssetQuery) NotAny(ps ...session.Pred) SessionWithAssetQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p SessionWithAssetQuery) Order(ts ...session.Sort) SessionWithAssetQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p SessionWithAssetQuery) Limit(n int64) SessionWithAssetQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p SessionWithAssetQuery) Offset(n int64) SessionWithAssetQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p SessionWithAssetQuery) After(r SessionWithAssetRow) SessionWithAssetQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p SessionWithAssetQuery) Err() error { return p.q.Err() }

// All runs the plan in exactly TWO round trips. Distinct parent keys are
// de-duplicated before the second, so a thousand rows pointing at three
// orgs fetch three orgs.
func (p SessionWithAssetQuery) All(ctx context.Context, ex runtime.Executor) ([]SessionWithAssetRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]SessionWithAssetRow, len(parents))
	seen := make(map[[16]byte]bool, len(parents))
	ids := make([][16]byte, 0, len(parents))
	for i, r := range parents {
		out[i] = SessionWithAssetRow{Row: r}
		key, ok := r.AssetID.Get()
		if !ok {
			continue
		}
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return out, nil
	}
	targets, err := asset.New().Unordered().
		Where(asset.ID.In(ids...)).
		Limit(int64(len(ids))).
		All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key, ok := out[i].AssetID.Get()
		if !ok {
			continue
		}
		j, ok := by[key]
		if !ok {
			// A foreign key pointing at a row that is not there. The database
			// forbids it, so reaching this means the constraint was dropped.
			return nil, fmt.Errorf("storm: %s references a missing %s row", "sessions", "assets")
		}
		out[i].Asset = &targets[j]
	}
	return out, nil
}
