// Code generated by storm v0.6.6. DO NOT EDIT.
//
// The compile-time staleness check: if a model's fields changed and this
// file was not regenerated, the package below does not build.
package rgen

import (
	m0 "github.com/gsoultan/argus/internal/control/rmodel"
)

// _assertAccessRequestShape fails to compile if m0.AccessRequest gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertAccessRequestShape(m m0.AccessRequest) {
	type shape m0.AccessRequest
	_ = shape{
		m.ID,
		m.RequesterEmail,
		m.AssetHostnames,
		m.Principal,
		m.Justification,
		m.DurationMinutes,
		m.State,
		m.CreatedAt,
		m.DecidedAt,
		m.DecidedByEmail,
		m.DecisionNote,
		m.ExpiresAt,
		m.BreakGlass,
	}
}

// _assertAgentShape fails to compile if m0.Agent gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertAgentShape(m m0.Agent) {
	type shape m0.Agent
	_ = shape{
		m.Hostname,
		m.Version,
		m.LastSeenAt,
		m.ActiveSessions,
		m.Posture,
		m.UpdatedAt,
		m.MatchedAsset,
		m.Fqdn,
		m.MachineID,
		m.Os,
		m.Addresses,
		m.Accounts,
		m.SshPorts,
		m.EnrollmentState,
		m.ReviewNote,
		m.ReviewedBy,
		m.ReviewedAt,
		m.FirstSeenAt,
		m.ExecTracing,
		m.ExecReason,
	}
}

// _assertAssetShape fails to compile if m0.Asset gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertAssetShape(m m0.Asset) {
	type shape m0.Asset
	_ = shape{
		m.Model,
		m.Hostname,
		m.Address,
		m.Port,
		m.Os,
		m.Tags,
		m.GroupName,
		m.CredentialMode,
		m.CredentialRotatedAt,
		m.RotationIntervalDays,
		m.HostKeyState,
		m.HostKeyFingerprint,
		m.HostKeyPinnedAt,
		m.Health,
		m.LastCheckedAt,
		m.Principals,
		m.AgentState,
		m.AgentLastSeenAt,
		m.BypassPosture,
		m.UnmanagedKeyCount,
		m.AgentHostname,
		m.DiscoveredBy,
		m.Protocol,
	}
}

// _assertAuditEventShape fails to compile if m0.AuditEvent gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertAuditEventShape(m m0.AuditEvent) {
	type shape m0.AuditEvent
	_ = shape{
		m.Seq,
		m.ID,
		m.At,
		m.Action,
		m.Severity,
		m.ActorEmail,
		m.Target,
		m.Detail,
		m.PrevHash,
		m.Hash,
	}
}

// _assertGatewayPolicyShape fails to compile if m0.GatewayPolicy gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertGatewayPolicyShape(m m0.GatewayPolicy) {
	type shape m0.GatewayPolicy
	_ = shape{
		m.ID,
		m.AllowLocalForward,
		m.AllowRemoteForward,
		m.AllowAgentForward,
		m.AllowX11Forward,
		m.ProxySftpSubsystem,
		m.FailClosedOnRecordingLoss,
		m.RequireEbpfForRoot,
		m.UpdatedAt,
		m.UpdatedBy,
	}
}

// _assertHostKeyPinShape fails to compile if m0.HostKeyPin gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertHostKeyPinShape(m m0.HostKeyPin) {
	type shape m0.HostKeyPin
	_ = shape{
		m.Host,
		m.Fingerprint,
		m.KeyType,
		m.PinnedAt,
		m.PinnedBy,
	}
}

// _assertRecoveryCodeShape fails to compile if m0.RecoveryCode gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertRecoveryCodeShape(m m0.RecoveryCode) {
	type shape m0.RecoveryCode
	_ = shape{
		m.User,
		m.CodeHash,
		m.CreatedAt,
		m.UsedAt,
	}
}

// _assertRedeemedTicketShape fails to compile if m0.RedeemedTicket gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertRedeemedTicketShape(m m0.RedeemedTicket) {
	type shape m0.RedeemedTicket
	_ = shape{
		m.ID,
		m.Email,
		m.Target,
		m.Principal,
		m.RedeemedAt,
		m.ExpiresAt,
	}
}

// _assertSchemaMigrationShape fails to compile if m0.SchemaMigration gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertSchemaMigrationShape(m m0.SchemaMigration) {
	type shape m0.SchemaMigration
	_ = shape{
		m.Name,
		m.AppliedAt,
	}
}

// _assertSessionShape fails to compile if m0.Session gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertSessionShape(m m0.Session) {
	type shape m0.Session
	_ = shape{
		m.ID,
		m.UserEmail,
		m.Asset,
		m.AssetHostname,
		m.Principal,
		m.Protocol,
		m.Origin,
		m.OriginReason,
		m.State,
		m.StartedAt,
		m.EndedAt,
		m.ClientIP,
		m.Fidelity,
		m.RecordingBytes,
		m.RecordingPath,
		m.CommandCount,
		m.ExitCode,
		m.ChainHead,
		m.RiskFlags,
		m.ReportedBy,
		m.CreatedAt,
		m.RecordingKey,
		m.TerminatedBy,
		m.TerminationReason,
	}
}

// _assertUserShape fails to compile if m0.User gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertUserShape(m m0.User) {
	type shape m0.User
	_ = shape{
		m.ID,
		m.Email,
		m.DisplayName,
		m.Role,
		m.MfaEnrolled,
		m.LastSeenAt,
		m.CreatedAt,
		m.PasswordHash,
		m.TotpSecret,
		m.MfaEnrolledAt,
		m.DisabledAt,
	}
}
