// Code generated by `storm import`. EDIT THIS.
//
// It is a first draft of the model behind an existing database, not a
// finished one: a Go declaration cannot express everything a schema knows,
// and the rest has to be added by hand. Nothing below is guessed silently —
// what did not survive the round trip is listed here.
//
// Nothing was dropped: every construct in this schema is expressible.

package rmodel

import (
	"time"

	"github.com/gsoultan/storm"
)

// AccessRequest is table access_requests.
type AccessRequest struct {
	ID              [16]byte
	RequesterEmail  string
	AssetHostnames  []string
	Principal       string
	Justification   string
	DurationMinutes int32
	State           string
	CreatedAt       time.Time
	DecidedAt       *time.Time
	DecidedByEmail  *string
	DecisionNote    *string
	ExpiresAt       *time.Time
	BreakGlass      bool
}

func (m *AccessRequest) Schema(t *storm.Table) {
	t.Col(&m.ID).Default("gen_random_uuid()")
	t.Col(&m.AssetHostnames).Default("'{}'::text[]")
	t.Col(&m.State).Default("'pending'::text")
	t.Col(&m.CreatedAt).Default("now()")
	t.Col(&m.BreakGlass).Default("false")
}

// Agent is table agents.
type Agent struct {
	Hostname        string
	Version         string
	LastSeenAt      time.Time
	ActiveSessions  int32
	Posture         *storm.JSON
	UpdatedAt       time.Time
	MatchedAsset    bool
	Fqdn            *string
	MachineID       *string
	Os              string
	Addresses       []string
	Accounts        []string
	SshPorts        []int32
	EnrollmentState string
	ReviewNote      string
	ReviewedBy      *string
	ReviewedAt      *time.Time
	FirstSeenAt     time.Time
	ExecTracing     bool
	ExecReason      string
}

func (m *Agent) Schema(t *storm.Table) {
	t.Col(&m.Version).Default("''::text")
	t.Col(&m.LastSeenAt).Default("now()")
	t.Col(&m.ActiveSessions).Default("0")
	t.Col(&m.UpdatedAt).Default("now()")
	t.Col(&m.MatchedAsset).Default("false")
	t.Col(&m.Os).Default("''::text")
	t.Col(&m.Addresses).Default("'{}'::text[]")
	t.Col(&m.Accounts).Default("'{}'::text[]")
	t.Col(&m.SshPorts).Default("'{}'::integer[]")
	t.Col(&m.EnrollmentState).Default("'unreviewed'::text")
	t.Col(&m.ReviewNote).Default("''::text")
	t.Col(&m.FirstSeenAt).Default("now()")
	t.Col(&m.ExecTracing).Default("false")
	t.Col(&m.ExecReason).Default("''::text")
	t.Index(storm.Desc(&m.LastSeenAt)).Where("(matched_asset = false) AND (enrollment_state = 'unreviewed'::text)").Named("agents_unreviewed_idx")
	t.Index(&m.Hostname).Where("exec_tracing").Named("agents_exec_tracing_idx")
}

// Asset is table assets.
type Asset struct {
	storm.Model

	Hostname             string
	Address              string
	Port                 int32
	Os                   string
	Tags                 []string
	GroupName            string
	CredentialMode       string
	CredentialRotatedAt  *time.Time
	RotationIntervalDays *int32
	HostKeyState         string
	HostKeyFingerprint   *string
	HostKeyPinnedAt      *time.Time
	Health               string
	LastCheckedAt        time.Time
	Principals           []string
	AgentState           string
	AgentLastSeenAt      *time.Time
	BypassPosture        string
	UnmanagedKeyCount    int32
	AgentHostname        *string
	DiscoveredBy         *string
	Protocol             string
}

func (m *Asset) Schema(t *storm.Table) {
	t.Col(&m.Port).Default("22")
	t.Col(&m.Os).Default("''::text")
	t.Col(&m.Tags).Default("'{}'::text[]")
	t.Col(&m.GroupName).Default("'ungrouped'::text")
	t.Col(&m.CredentialMode).Default("'injected-key'::text")
	t.Col(&m.HostKeyState).Default("'unpinned'::text")
	t.Col(&m.Health).Default("'reachable'::text")
	t.Col(&m.LastCheckedAt).Default("now()")
	t.Col(&m.Principals).Default("'{}'::text[]")
	t.Col(&m.AgentState).Default("'absent'::text")
	t.Col(&m.BypassPosture).Default("'open'::text")
	t.Col(&m.UnmanagedKeyCount).Default("0")
	t.Col(&m.Protocol).Default("'ssh'::text")
	t.UniqueNamed("assets_hostname_key", &m.Hostname)
	t.Index(&m.AgentHostname).Unique().Where("agent_hostname IS NOT NULL").Named("assets_agent_hostname_idx")
	t.Index(&m.Protocol).Named("assets_protocol_idx")
}

// AuditEvent is table audit_events.
type AuditEvent struct {
	Seq        int64
	ID         [16]byte
	At         time.Time
	Action     string
	Severity   string
	ActorEmail string
	Target     string
	Detail     string
	PrevHash   string
	Hash       string
}

func (m *AuditEvent) Schema(t *storm.Table) {
	t.Col(&m.Seq).Serial()
	t.Col(&m.ID).Default("gen_random_uuid()")
	t.Col(&m.At).Default("now()")
	t.Col(&m.Severity).Default("'info'::text")
	t.Col(&m.ActorEmail).Default("''::text")
	t.Col(&m.Target).Default("''::text")
	t.Col(&m.Detail).Default("''::text")
	t.Index(storm.Desc(&m.At)).Named("audit_at_idx")
	t.Index(&m.Severity).Named("audit_severity_idx")
}

// GatewayPolicy is table gateway_policy.
//
// The table name is not what storm would derive from the type, so it is
// set explicitly in Schema — otherwise the first diff would rename it.
type GatewayPolicy struct {
	ID                        bool
	AllowLocalForward         bool
	AllowRemoteForward        bool
	AllowAgentForward         bool
	AllowX11Forward           bool
	ProxySftpSubsystem        bool
	FailClosedOnRecordingLoss bool
	RequireEbpfForRoot        bool
	UpdatedAt                 time.Time
	UpdatedBy                 string
}

func (m *GatewayPolicy) Schema(t *storm.Table) {
	t.Name("gateway_policy")
	t.Col(&m.ID).Default("true")
	t.Col(&m.AllowLocalForward).Default("false")
	t.Col(&m.AllowRemoteForward).Default("false")
	t.Col(&m.AllowAgentForward).Default("false")
	t.Col(&m.AllowX11Forward).Default("false")
	t.Col(&m.ProxySftpSubsystem).Default("true")
	t.Col(&m.FailClosedOnRecordingLoss).Default("true")
	t.Col(&m.RequireEbpfForRoot).Default("true")
	t.Col(&m.UpdatedAt).Default("now()")
	t.Col(&m.UpdatedBy).Default("''::text")
	t.CheckNamed("gateway_policy_id_check", "id")
}

// HostKeyPin is table host_key_pins.
type HostKeyPin struct {
	Host        string
	Fingerprint string
	KeyType     string
	PinnedAt    time.Time
	PinnedBy    string
}

func (m *HostKeyPin) Schema(t *storm.Table) {
	t.Col(&m.KeyType).Default("''::text")
	t.Col(&m.PinnedAt).Default("now()")
	t.Col(&m.PinnedBy).Default("''::text")
}

// RecoveryCode is table recovery_codes.
type RecoveryCode struct {
	User      User
	CodeHash  string
	CreatedAt time.Time
	UsedAt    *time.Time
}

func (m *RecoveryCode) Schema(t *storm.Table) {
	t.Col(&m.User).ConstraintName("recovery_codes_user_id_fkey")
	t.Col(&m.User).OnDelete(storm.Cascade)
	t.Col(&m.CreatedAt).Default("now()")
	t.Index(&m.User).Where("used_at IS NULL").Named("recovery_codes_user_idx")
}

// RedeemedTicket is table redeemed_tickets.
type RedeemedTicket struct {
	ID         string
	Email      string
	Target     string
	Principal  string
	RedeemedAt time.Time
	ExpiresAt  time.Time
}

func (m *RedeemedTicket) Schema(t *storm.Table) {
	t.Col(&m.Email).Default("''::text")
	t.Col(&m.Target).Default("''::text")
	t.Col(&m.Principal).Default("''::text")
	t.Col(&m.RedeemedAt).Default("now()")
	t.Index(&m.ExpiresAt).Named("redeemed_tickets_expiry_idx")
}

// SchemaMigration is table schema_migrations.
type SchemaMigration struct {
	Name      string
	AppliedAt time.Time
}

func (m *SchemaMigration) Schema(t *storm.Table) {
	t.Col(&m.AppliedAt).Default("now()")
}

// Session is table sessions.
type Session struct {
	ID             [16]byte
	UserEmail      string
	Asset          *Asset
	AssetHostname  string
	Principal      string
	Protocol       string
	Origin         string
	OriginReason   *string
	State          string
	StartedAt      time.Time
	EndedAt        *time.Time
	ClientIP       string
	Fidelity       string
	RecordingBytes int64
	RecordingPath  *string
	CommandCount   *int32
	ExitCode       *int32
	ChainHead      *string
	RiskFlags      []string
	ReportedBy     string
	CreatedAt      time.Time
	RecordingKey   *string

	TerminatedBy      *string
	TerminationReason *string
}

func (m *Session) Schema(t *storm.Table) {
	t.Col(&m.Asset).ConstraintName("sessions_asset_id_fkey")
	t.Col(&m.Asset).OnDelete(storm.SetNull)
	t.Col(&m.Protocol).Default("'ssh'::text")
	t.Col(&m.Origin).Default("'brokered'::text")
	t.Col(&m.State).Default("'active'::text")
	t.Col(&m.ClientIP).Default("''::text")
	t.Col(&m.Fidelity).Default("'pty'::text")
	t.Col(&m.RecordingBytes).Default("0")
	t.Col(&m.RiskFlags).Default("'{}'::text[]")
	t.Col(&m.ReportedBy).Default("''::text")
	t.Col(&m.CreatedAt).Default("now()")
	t.Index(&m.Asset).Named("sessions_asset_id_idx")
	t.Index(storm.Desc(&m.StartedAt)).Where("origin = 'direct'::text").Named("sessions_direct_idx")
	t.Index(storm.Desc(&m.StartedAt)).Named("sessions_started_idx")
	t.Index(&m.State).Named("sessions_state_idx")
	t.Index(&m.TerminatedBy).Where("terminated_by IS NOT NULL").Named("sessions_terminated_idx")
}

// User is table users.
type User struct {
	ID            [16]byte
	Email         string
	DisplayName   string
	Role          string
	IdpSubject    *string
	MfaEnrolled   bool
	LastSeenAt    *time.Time
	CreatedAt     time.Time
	PasswordHash  *string
	TotpSecret    *string
	MfaEnrolledAt *time.Time
	DisabledAt    *time.Time
}

func (m *User) Schema(t *storm.Table) {
	t.Col(&m.ID).Default("gen_random_uuid()")
	t.Col(&m.Role).Default("'operator'::text")
	t.Col(&m.MfaEnrolled).Default("false")
	t.Col(&m.CreatedAt).Default("now()")
	t.UniqueNamed("users_email_key", &m.Email)
	t.Index(storm.Lower(&m.Email)).Unique().Named("users_email_lower_key")
}

// All is what you pass to storm.Build.
func All() []any {
	return []any{
		&AccessRequest{},
		&Agent{},
		&Asset{},
		&AuditEvent{},
		&GatewayPolicy{},
		&HostKeyPin{},
		&RecoveryCode{},
		&RedeemedTicket{},
		&SchemaMigration{},
		&Session{},
		&User{},
	}
}
